### ISSUE TITLE
optimizationLevel

### ISSUE THREAD

**Issue by FilipeQ** [imagemin/imagemin-gifsicle#11]
The property optimizationLevel reduce size of .gif? Because i have a big gif and i want reduce their size but api save the gif with same size.

**Comment by shinnn** [comment]
1. Needs more info (OS, OS version, Node version, npm version, npm package versions, ...)
2. Can you optimize your .gif file directly with [`gifsicle`](https://www.lcdf.org/gifsicle/) binary and tell us whether it reduces file size or not? If the binary can reduce file size but this plugin doesn't, indeed this is an imagemin-gifsicle issue. Otherwise, this question should be posted on https://github.com/kohler/gifsicle/issues instead.

**Comment by FilipeQ** [comment]
With binary gifscile i get some warning **(too many colors, using local colorsmaps. You may want to try --colors 256)** after i use this property in comand line the gif was compressed. But api don't have this property.

**Comment by shinnn** [comment]
@FilipeQ Thanks for the report. Would you mind making a PR to add `color` option to this plugin?

**Comment by FilipeQ** [comment]
Done
